In [ ]:
#Program-5
""""
Write a program to demonstrate Decision tree regression for a given dataset.(Play_Tennis_reg)
""""

In [2]:
# Load libraries
import numpy as np
import pandas as pd
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [3]:
df=pd.read_csv(r"C:/Users/admin/Downloads/CSE 5/Visual Studio Code/python files/ML LAB/Trainingdata6.csv")
df

    Day   Outlook Temprature Humidity    Wind Play_Tennis
0    D1     Sunny        Hot     High    Weak          No
1    D2     Sunny        Hot     High  Strong          No
2    D3  Overcast        Hot     High    Weak         Yes
3    D4      Rain       Mild     High    Weak         Yes
4    D5      Rain       Cool   Normal    Weak         Yes
5    D6      Rain       Cool   Normal  Strong          No
6    D7  Overcast       Cool   Normal  Strong         Yes
7    D8     Sunny       Mild     High    Weak          No
8    D9     Sunny       Cool   Normal    Weak         Yes
9   D10      Rain       Mild   Normal    Weak         Yes
10  D11     Sunny       Mild   Normal  Strong         Yes
11  D12  Overcast       Mild     High  Strong         Yes
12  D13  Overcast        Hot   Normal    Weak         Yes
13  D14      Rain       Mild     High  Strong          No

In [5]:
len(df)

14

In [6]:
df.shape  #To see the number of rows and columns in our dataset:

(14, 6)

In [4]:
from sklearn import preprocessing
string_to_int= preprocessing.LabelEncoder()                     #encode your data
df = df.apply(string_to_int.fit_transform) #fit and transform it
df

    Day  Outlook  Temprature  Humidity  Wind  Play_Tennis
0     0        2           1         0     1            0
1     6        2           1         0     0            0
2     7        0           1         0     1            1
3     8        1           2         0     1            1
4     9        1           0         1     1            1
5    10        1           0         1     0            0
6    11        0           0         1     0            1
7    12        2           2         0     1            0
8    13        2           0         1     1            1
9     1        1           2         1     1            1
10    2        2           2         1     0            1
11    3        0           2         0     0            1
12    4        0           1         1     1            1
13    5        1           2         0     0            0

In [6]:
#To divide our data into attribute set and Label:
feature_cols = ['Outlook','Temprature','Humidity','Wind']
X = df[feature_cols ]                               #contains the attribute 
y = df.Play_Tennis
#print(X,y)

In [11]:
from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor()
reg = reg.fit(X, y)

In [40]:
new_df = pd.DataFrame([[0,0,0,0]],columns=['Outlook','Temprature','Humidity','Wind'])
y_pred = reg.predict(new_df)
# print the Result 
print("Result is: ", y_pred)

Result is:  [1.]

In [8]:
new_df = pd.DataFrame([[0,0,1,1]],columns=['Outlook','Temprature','Humidity','Wind'])
y_pred = reg.predict(new_df)
# print the Result 
print("Result is: ", y_pred)

Result is:  [1.]

In [9]:
new_df = pd.DataFrame([[2,1,0,0]],columns=['Outlook','Temprature','Humidity','Wind'])
y_pred = reg.predict(new_df)
# print the Result 
print("Result is: ", y_pred)

Result is:  [0.]